fail_fast: false
repos:
  - repo: https://github.com/Takishima/cmake-pre-commit-hooks
    rev: 'v1.5.2'
    hooks:
      - id: clang-format
        args: [-i]
      - id: clang-tidy
        args: [--fix]
